---
- name: download plex
  get_url:
    url: https://downloads.plex.tv/plex-media-server/1.13.0.5023-31d3c0c65/plexmediaserver_1.13.0.5023-31d3c0c65_amd64.deb
    dest: /home/chuleh
    mode: 0440

- name: install plex
  dpkg_selections:
    name: plexmediaserver_1.13.0.5023-31d3c0c65_amd64.deb
    selection: install

- name: start plex
  service:
    name: plexmediaserver
    state: started

